sonar.projectKey=idrisadisa_idrisadisa-devsecops
sonar.projectName=idrisadisa-devsecops
sonar.organization=idrisadisa
sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/package-lock.json
